# Exported from Render on 2024-07-07T20:26:45Z
services:
  - type: web
    name: Pyintel-Code-Server
    runtime: node
    repo: https://github.com/riteshrajas/Pyintel-Code-Server
    plan: free
    envVars:
      - key: PORT
        sync: false
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
version: "1"
